spring:
  application:
    name: actuator

management:
  server:
    port: 9999
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 9999
